// src/routes/error/+page.svelte
<script lang="ts">
import type { AppLocale } from "@/i18n/config";
import { getOAuthCopy } from "@/lib/oauth-copy";
import { page } from "$app/stores";
import { Button } from "$lib/components/ui/button/index.js";
import * as Card from "$lib/components/ui/card/index.js";

$: copy = getOAuthCopy(($page.data.locale ?? "zh-cn") as AppLocale);
$: errorCode = $page.url.searchParams.get("error");
$: message =
  errorCode === "consent_failed" ? copy.errorConsentFailed : copy.errorGeneric;
</script>

<svelte:head><title>{copy.errorPageTitle} - Life@USTC</title></svelte:head>

<main class="grid min-h-[calc(100vh-8rem)] place-items-center px-4">
  <Card.Root class="w-full max-w-md">
    <Card.Header class="text-center">
      <Card.Title class="text-2xl">{copy.errorPageTitle}</Card.Title>
      <Card.Description>{message}</Card.Description>
    </Card.Header>
    <Card.Content class="grid justify-items-center gap-4 text-center text-base-content/60 text-sm">
      <p>
        {copy.errorPageHint}
      </p>
      <Button href="/" variant="outline">{copy.returnHome}</Button>
    </Card.Content>
  </Card.Root>
</main>

// src/app/error/page.tsx
import type { Metadata } from "next";
import { getTranslations } from "next-intl/server";
import {
  Card,
  CardDescription,
  CardHeader,
  CardPanel,
  CardTitle,
} from "@/components/ui/card";

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations("oauth");
  return { title: t("errorPageTitle") };
}

export default async function ErrorPage({
  searchParams,
}: {
  searchParams: Promise<{ error?: string }>;
}) {
  const [{ error }, t] = await Promise.all([
    searchParams,
    getTranslations("oauth"),
  ]);

  const message =
    error === "consent_failed" ? t("errorConsentFailed") : t("errorGeneric");

  return (
    <main className="page-main flex min-h-[calc(100vh-8rem)] items-center justify-center">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <CardTitle className="text-2xl">{t("errorPageTitle")}</CardTitle>
          <CardDescription>{message}</CardDescription>
        </CardHeader>
        <CardPanel className="text-center text-muted-foreground text-sm">
          {t("errorPageHint")}
        </CardPanel>
      </Card>
    </main>
  );
}
