// src/components/comments/comment-link-cards.tsx
"use client";

import { useTranslations } from "next-intl";
import { useMemo } from "react";
import { Card, CardPanel } from "@/components/ui/card";
import { Link } from "@/i18n/routing";

type LinkCard = {
  href: string;
  label: string;
  description?: string | null;
};

const urlPattern = /\bhttps?:\/\/[^\s<>()]+/gi;
const mentionPattern = /\b(section|teacher)#(\d+)\b/gi;

function extractLinkCards(
  content: string | undefined | null,
  t: ReturnType<typeof useTranslations>,
) {
  if (!content) return [];
  const cards: LinkCard[] = [];
  const seen = new Set<string>();

  for (const match of content.matchAll(mentionPattern)) {
    const kind = match[1];
    const id = match[2];
    const href = kind === "teacher" ? `/teachers/${id}` : `/sections/${id}`;
    if (seen.has(href)) continue;
    seen.add(href);
    cards.push({
      href,
      label:
        kind === "teacher"
          ? t("linkTeacher", { id })
          : t("linkSection", { id }),
      description: t("linkHost"),
    });
  }

  for (const match of content.matchAll(urlPattern)) {
    const href = match[0];
    if (seen.has(href)) continue;
    try {
      const url = new URL(href);
      if (url.hostname !== "life.ustc.tiankaima.dev") continue;
      seen.add(href);
      cards.push({
        href,
        label: url.pathname || href,
        description: url.hostname,
      });
    } catch {}
  }

  return cards;
}

type CommentLinkCardsProps = {
  content?: string | null;
};

export function CommentLinkCards({ content }: CommentLinkCardsProps) {
  const t = useTranslations("comments");
  const cards = useMemo(() => extractLinkCards(content, t), [content, t]);
  if (cards.length === 0) return null;

  return (
    <div className="mt-3 grid gap-2 sm:grid-cols-2">
      {cards.map((card) => (
        <Card key={card.href} className="gap-2 py-4">
          <CardPanel className="space-y-1">
            <Link href={card.href} className="text-sm font-medium">
              {card.label}
            </Link>
            {card.description && (
              <p className="text-xs text-muted-foreground">
                {card.description}
              </p>
            )}
          </CardPanel>
        </Card>
      ))}
    </div>
  );
}

// src/features/comments/components/CommentLinkCards.svelte
<script lang="ts">
import * as Card from "$lib/components/ui/card/index.js";

type LinkCard = {
  description: string;
  href: string;
  label: string;
};

type CommentLinkCardsCopy = {
  linkHost: string;
  linkSection: string;
  linkTeacher: string;
};

export let content: string | null | undefined = "";
export let copy: CommentLinkCardsCopy;

const urlPattern = /\bhttps?:\/\/[^\s<>()]+/gi;
const mentionPattern = /\b(section|teacher)#(\d+)\b/gi;

function trimTrailingPunctuation(value: string) {
  return value.replace(/[.,;:!?，。；：！？]+$/u, "");
}

function labelFromTemplate(template: string, id: string) {
  return template.replace("{id}", id);
}

function extractLinkCards(
  value: string | null | undefined,
  labels: CommentLinkCardsCopy,
) {
  if (!value) return [];
  const cards: LinkCard[] = [];
  const seen = new Set<string>();

  for (const match of value.matchAll(mentionPattern)) {
    const kind = match[1]?.toLowerCase();
    const id = match[2] ?? "";
    const href = kind === "teacher" ? `/teachers/${id}` : `/sections/${id}`;
    if (seen.has(href)) continue;
    seen.add(href);
    cards.push({
      description: labels.linkHost,
      href,
      label: labelFromTemplate(
        kind === "teacher" ? labels.linkTeacher : labels.linkSection,
        id,
      ),
    });
  }

  for (const match of value.matchAll(urlPattern)) {
    const href = trimTrailingPunctuation(match[0]);
    if (seen.has(href)) continue;
    try {
      const url = new URL(href);
      if (
        url.hostname !== "life.ustc.tiankaima.dev" &&
        url.hostname !== globalThis.location?.hostname
      ) {
        continue;
      }
      seen.add(href);
      cards.push({
        description: url.hostname,
        href,
        label: url.pathname || href,
      });
    } catch {
      // Ignore malformed URLs matched from user content.
    }
  }

  return cards;
}

$: cards = extractLinkCards(content, copy);
</script>

{#if cards.length > 0}
  <div class="mt-3 grid gap-2 sm:grid-cols-2">
    {#each cards as card}
      <Card.Root class="border-base-300 bg-base-100 shadow-none">
        <Card.Content class="grid gap-1 p-3">
          <a class="font-medium text-primary text-sm hover:underline" href={card.href}>
            {card.label}
          </a>
          <p class="text-base-content/60 text-xs">{card.description}</p>
        </Card.Content>
      </Card.Root>
    {/each}
  </div>
{/if}
