// src/components/comments/markdown-editor.tsx
"use client";

import type * as React from "react";
import { useState } from "react";
import { CommentMarkdown } from "@/components/comments/comment-markdown";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTab } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Link } from "@/i18n/routing";
import { cn } from "@/lib/utils";

type MarkdownEditorProps = {
  value: string;
  onChange: (value: string) => void;
  placeholder: string;
  tabWriteLabel: string;
  tabPreviewLabel: string;
  previewEmptyLabel: string;
  markdownGuideLabel: string;
  markdownGuideHref: string;
  disabled?: boolean;
  rows?: number;
  compact?: boolean;
  isDragActive?: boolean;
  onDragOver?: React.DragEventHandler<HTMLTextAreaElement>;
  onDragLeave?: React.DragEventHandler<HTMLTextAreaElement>;
  onDrop?: React.DragEventHandler<HTMLTextAreaElement>;
  onKeyDown?: React.KeyboardEventHandler<HTMLTextAreaElement>;
  textareaRef?: React.Ref<HTMLTextAreaElement>;
};

export function MarkdownEditor({
  value,
  onChange,
  placeholder,
  tabWriteLabel,
  tabPreviewLabel,
  previewEmptyLabel,
  markdownGuideLabel,
  markdownGuideHref,
  disabled,
  rows,
  compact,
  isDragActive,
  onDragOver,
  onDragLeave,
  onDrop,
  onKeyDown,
  textareaRef,
}: MarkdownEditorProps) {
  const [activeTab, setActiveTab] = useState("write");
  const resolvedRows = rows ?? (compact ? 3 : 6);

  return (
    <div className="space-y-3">
      <Tabs
        value={activeTab}
        onValueChange={(next) => next && setActiveTab(next)}
        className="w-full"
      >
        <div className="mb-2 flex items-end justify-between gap-2">
          <TabsList className="h-8 bg-muted/50 p-0.5">
            <TabsTab value="write" className="h-7 px-3 text-xs">
              {tabWriteLabel}
            </TabsTab>
            <TabsTab value="preview" className="h-7 px-3 text-xs">
              {tabPreviewLabel}
            </TabsTab>
          </TabsList>
        </div>

        <div
          className={cn(
            "min-h-[8rem] rounded-xl border bg-muted/10 transition-shadow",
            activeTab === "write" &&
              "focus-within:border-primary/50 focus-within:ring-[3px] focus-within:ring-primary/10",
          )}
        >
          <div
            className={cn("flex flex-col", activeTab !== "write" && "hidden")}
          >
            <Textarea
              ref={textareaRef}
              value={value}
              onChange={(event) => onChange(event.target.value)}
              aria-label={placeholder}
              placeholder={placeholder}
              rows={resolvedRows}
              disabled={disabled}
              unstyled
              className={cn(
                "w-full resize-none bg-transparent p-4 text-sm",
                isDragActive ? "bg-primary/5" : "",
              )}
              onDragOver={onDragOver}
              onDragLeave={onDragLeave}
              onDrop={onDrop}
              onKeyDown={onKeyDown}
            />
          </div>
          <div className={cn("p-4", activeTab !== "preview" && "hidden")}>
            {value.trim() ? (
              <CommentMarkdown content={value} />
            ) : (
              <p className="text-center text-muted-foreground text-xs italic">
                {previewEmptyLabel}
              </p>
            )}
          </div>
        </div>

        <div className="mt-2 flex justify-end">
          <Button
            variant="ghost"
            size="xs"
            className="h-8 px-2 text-muted-foreground"
            render={<Link className="no-underline" href={markdownGuideHref} />}
          >
            <span className="text-xs">{markdownGuideLabel}</span>
          </Button>
        </div>
      </Tabs>
    </div>
  );
}

// src/lib/components/MarkdownEditor.svelte
<script lang="ts">
import MarkdownPreview from "$lib/components/MarkdownPreview.svelte";
import { Button } from "$lib/components/ui/button/index.js";
import * as Tabs from "$lib/components/ui/tabs/index.js";
import { Textarea } from "$lib/components/ui/textarea/index.js";

export let disabled = false;
export let guideHref = "/guides/markdown-support";
export let guideLabel = "";
export let isDragActive = false;
export let modeLabel = "";
export let name: string | undefined = undefined;
export let placeholder = "";
export let previewEmptyLabel = "";
export let rows = 6;
export let tabPreviewLabel = "";
export let tabWriteLabel = "";
export let value = "";
let activeTab: "write" | "preview" = "write";
let className = "";

export { className as class };
</script>

<div class={`grid gap-3 ${className}`} data-slot="markdown-editor">
  {#if name}
    <input type="hidden" {name} {value} />
  {/if}

  <Tabs.List aria-label={modeLabel}>
    <Tabs.Button
      selected={activeTab === "write"}
      onclick={() => {
        activeTab = "write";
      }}
    >
      {tabWriteLabel}
    </Tabs.Button>
    <Tabs.Button
      selected={activeTab === "preview"}
      onclick={() => {
        activeTab = "preview";
      }}
    >
      {tabPreviewLabel}
    </Tabs.Button>
  </Tabs.List>

  <div
    class={`min-h-32 rounded-md border border-base-300 bg-base-100 transition-colors focus-within:ring-2 focus-within:ring-primary/30 ${isDragActive ? "border-primary bg-primary/5" : ""}`}
  >
    {#if activeTab === "write"}
      <Textarea
        class="min-h-0 resize-y border-0 bg-transparent shadow-none focus-visible:ring-0"
        bind:value
        {disabled}
        {placeholder}
        {rows}
        {...$$restProps}
      ></Textarea>
    {:else}
      <div class="min-h-32 p-3">
        {#if value.trim()}
          <MarkdownPreview content={value} />
        {:else}
          <p class="text-center text-base-content/50 text-sm italic">
            {previewEmptyLabel}
          </p>
        {/if}
      </div>
    {/if}
  </div>

  {#if guideLabel}
    <div class="flex justify-end">
      <Button href={guideHref} size="sm" variant="ghost">{guideLabel}</Button>
    </div>
  {/if}
</div>
